---
jenkins_user: "jenkins"
jenkins_group: "jenkins"
jenkins_home: /home/jenkins

# repo for nodejs
jenkins_chrislea_ppa: "ppa:chris-lea/node.js"

jenkins_edx_platform_version: master

# System packages
jenkins_debian_pkgs:
    - nodejs
    - pkg-config
    - libffi-dev
    - python-dev
    - libsqlite3-dev

# packer direct download URL
packer_url: "https://releases.hashicorp.com/packer/0.8.6/packer_0.8.6_linux_amd64.zip"

# custom firefox
custom_firefox_version: 42.0
custom_firefox_url: "https://ftp.mozilla.org/pub/firefox/releases/{{ custom_firefox_version }}/linux-x86_64/en-US/firefox-{{ custom_firefox_version }}.tar.bz2"

# Pip-accel itself and other workarounds that need to be installed with pip
pip_accel_reqs:
  # Install Shapely with pip as it does not install cleanly
  # with pip-accel because it has a weird setup.py
  - "Shapely==1.2.16"
  # Install unittest2 which is needed by lettuce
  # but also pip-accel has trouble with determining that.
  # unittest2>=0.8.0 (from testtools>=0.9.34->python-subunit->lettuce==0.2.20)
  - "unittest2>=0.8.0"
  # There is a bug in pip 1.4.1 by which --exists-action is broken.
  # This is fixed in pip 1.5.x, but alas pip-accel is not yet compatible with pip 1.5.x.
  # Remove when we can upgrade to a version of pip-accel that supports pip 1.5.x.
  - "git+https://github.com/jzoldak/pip.git@v1.4.1patch772#egg=pip"
  # Install pip-accel itself (using pip)
  - "pip-accel==0.21.1"
  # pip-accel only makes the s3 functionality available if boto is installed
  - "boto=={{ common_boto_version }}"

# For each ubuntu release, the minimum kernel version to contain a patch for
# CVE-2016-5195. Note: for ease of dealing with the version_compare filter,
# "-"s have been replaced with "."s
patched_kernel_releases:
    - { os_release: '12.04', min_kernel_version: '3.2.0.113' }
    - { os_release: '14.04', min_kernel_version: '3.13.0.100' }
    - { os_release: '16.04', min_kernel_version: '4.4.0.45' }
    - { os_release: '16.10', min_kernel_version: '4.8.0.26' }
